#!/bin/sh

echo 'Copying kernel to floppy image'

cp base_images/floppy.img bin/
mkdir -p /mnt/floppy_image
losetup /dev/loop1 ./bin/floppy.img
mount -t msdos /dev/loop1 /mnt/floppy_image
cp ./bin/kernel0 /mnt/floppy_image
fuser /mnt/floppy_image
umount /mnt/floppy_image
losetup -d /dev/loop1
 
echo 'Copy complete'


