
#ifndef DMA_H
#define DMA_H

#define D1_STATUS_REGISTER			0X08
#define D1_COMMAND_REGISTER			0X08
#define D1_REQUEST_REGISTER			0X09
#define D1_CHANNEL_MASK_REGISTER	0X0A
#define D1_MODE_REGISTER			0x0B
#define D1_BYTEWORD_REGISTER		0x0C
#define D1_INTERMEDIATE_REGISTER	0X0D
#define D1_MASK_REGISTER			0X0F

#define D2_STATUS_REGISTER			0XD0
#define D2_COMMAND_REGISTER			0XD0
#define D2_REQUEST_REGISTER			0XD2
#define D2_CHANNEL_MASK_REGISTER	0XD4
#define D2_MODE_REGISTER			0xD6
#define D2_BYTEWORD_REGISTER		0xD8
#define D2_INTERMEDIATE_REGISTER	0XDA
#define D2_MASK_REGISTER			0XDE

#define MAX_DMA_CHANNELS	4
#define FLOPPY_DMA_ADDRESS 0x5000
#define FLOPPY_DMA_BUFFER_SIZE 512


#endif
